# site settings
title: Overpass
subtitle: Brass
email: booking@overpassbrass.com
description: New Orleans-inspired east-bay brass band
baseurl: "/overpassbrass" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
permalink: /:slug/
collections:
  posts:
    permalink: /:categories/:year/:month/:day/:title/

author:
street_address:
city: East Bay
state: California
zip_code:
country:
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn:
  Twitter:
  Facebook: https://www.facebook.com/UnderpassBrass
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- LICENSE.md
- README.md
- samples/
